title: Business Central Dokumentacija
description: Detaljno uputstvo za korišćenje dodatka za brzu poštu
theme: just-the-docs
color_scheme: dark
search_enabled: true
nav_external_links:
  - title: GitHub
    url: https://github.com/vasekorisnickoime/bc-docs
    hide_icon: false
